CREATE TABLE sales(
id SERIAL PRIMARY KEY,
product_name VARCHAR(100),
quantity INT,
price DOUBLE PRECISION,
region VARCHAR(50),
total DOUBLE PRECISION,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);